#!/bin/bash


filename=$(basename "$1")
extension="${filename##*.}"
filename="${filename%.*}"

clang -O0 -emit-llvm -c inputFiles/$1
opt -mem2reg $filename.bc -o $filename-simp.bc
opt -stats -load ./DeadCodeElimination.so -dead-code-elimination $filename-simp.bc -o $filename-out.bc

llvm-dis $filename-simp.bc
llvm-dis $filename-out.bc
